### ISSUE TITLE
.net core ?

### ISSUE THREAD

**Issue by MarkusGalant** [CityOfZion/neo-lux#12]
Hi guys .
Please tell me when your library is coming to .net ?

**Comment by Relfos** [comment]
I will to convert it to a .NET standard library as soon as possible.

**Comment by Relfos** [comment]
Hi, this is done in latest version, available at nuget, NeoLux 0.6.4

**Comment by Mr-zohaibkhalid** [comment]
hello sir .. im facing error on NeoDB .. Can you tell me how to solve it

**Comment by Relfos** [comment]
What error?
More info please
