### ISSUE TITLE
ScriptBuilder emitting trimmed hexstring

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neo-lux#13]
The ScriptBuilder is emitting a trimmed hexstring for BigInteger representation. Usually, the BigInteger is represented as a 16 character hexstring. Trimming may occur for excess zeroes. However, this trimming is causing an issue as the node seems to be unable to process the trimmed BigInteger.

Take for example, `78a1552b1a4cf1eb04a9cfa4998965603a0beb148a80354f0d2d58ef5aeb58c2` on testnet. The VM script uses a trimmed hexstring for the `amount` and the user reports that the transaction did not effect a change in tokens.

I had this experience in neon-js too and the solution was to always use 8 bytes to represent a BigInteger.

**Comment by Relfos** [comment]
I was investigating this now after reading the issue, as I checked that transaction, got the bytecode from it here:

https://neoscan-testnet.io/transaction/78a1552b1a4cf1eb04a9cfa4998965603a0beb148a80354f0d2d58ef5aeb58c2

Then I ran it through the official NEO VM, and the "amount" decodes correctly as a BigInteger with value 100000000000. 

Also the code I'm using to include a BigInteger in the transaction comes from the official source too:
https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/ScriptBuilder.cs#L48
The padding should make no difference and might be a red herring, the problem could lie in something else.

Could be a temporary network problem that made the tokens being reported as 0. I will investigate this further.

**Comment by Relfos** [comment]
Fixed token transfer, in the end there were 3 different problems affecting like, like lack of nonce added to each tx meaning repeated transfers from same address with same quantity would fail, also for some reason the order of the script parameters was incorrect, just even if tx would get accepted it would fail at VM level.
