### ISSUE TITLE
DemoForUnity has lots of error on building.

### ISSUE THREAD

**Issue by rct1985** [CityOfZion/neo-lux#18]
Thanks for your work.
There are some obvious errors in file "NeoDemo.cs". 
eg:
`using NeoLux;
using Neo;
using Neo.Cryptography;
using Neo.VM;`

Base on your lastest Neo-Lux it should like
`using Neo;
using Neo.Lux;
using Neo.Lux.Core;
using Neo.Lux.Utils;
using Neo.Lux.Cryptography;`

It will be greatly helpfull if you can fix them .
Thanks in advance

**Comment by JosephFrusetta** [comment]
This will fix most of the errors: 
`Build Settings > Player Settings > and set API compatibility level to .NET 4.6 `

Then Unity will error, "The type of namespace name 'Numerics' does not exist. So you need to go to the following location and do a search for numerics.  `C:\Program Files\Unity\Editor\Data\MonoBleedingEdge\lib\mono\4.5\'

Then copy/past the file into
'neo-lux-master\Demos\NeoUnity\Assets' 

Now you're at the point where I am stuck. You'll have two more errors:

`Assets/Scripts/NeoDemo.cs(283,61): error CS1061: Type `byte[]' does not contain a definition for `AES256Encrypt' and no extension method `AES256Encrypt' of type `byte[]' could be found. Are you missing an assembly reference?`

`Assets/Scripts/NeoDemo.cs(331,37): error CS1061: Type `byte[]' does not contain a definition for `AES256Decrypt' and no extension method `AES256Decrypt' of type `byte[]' could be found. Are you missing an assembly reference?`

I tried messing around with the code commented at the top of the script to see if this might help, but I wasn't able to get anything done with it. 
'/* 	PlayerPrefs Structure
 * ====================================================
 * 	Default Account:
 * 		"neoAccount": "literalAccountName"
 * 	Encrypted WIF Location:
 * 		"literalAccountName": "literalEncryptedWif"
*/
'


If we want more people to be making games with NEO / GAS this demo should work without any extra steps, or at the very least all the necessary extra steps should be added to the README.

**Comment by Relfos** [comment]
Fixed in latest commit.
