### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by arkoc** [CityOfZion/neo-lux#20]
I can see from source code that `.NET Core` standard is added, but I guess it isn't published to nuget. 

Are you planning to publish it ?

**Comment by Relfos** [comment]
Yes, in next version that will be added in Nuget

**Comment by arkoc** [comment]
Can you share approximately when you are going to update Nuget ?

Thanks.

**Comment by Relfos** [comment]
Tomorrow if possible

**Comment by Relfos** [comment]
Already did. Version 0.7.5 supports .NET core
