### ISSUE TITLE
How to get a DataNode On a CallContract

### ISSUE THREAD

**Issue by rct1985** [CityOfZion/neo-lux#26]
# Thanks for your wonderful work
It's realy helpful on working with unity. 
I want to get a datanode object on calling a method from contract. 
but now I got a transaction from which nothing usedfull data is included.

Any advice is appreciated.

**Comment by Relfos** [comment]
Sadly at least for now when calling a contract the only thing you obtain back is a transaction. I recommend writing to the storage and then read the storage back with api.GetStorage

**Comment by rct1985** [comment]
Got it, thanks so mush!
