### ISSUE TITLE
Add MyWish to NeoRPC.cs file under ForPrivateNet method

### ISSUE THREAD

**Issue by alibugra** [CityOfZion/neo-lux#32]
Hi all,

I would like to add MyWish (http://neoscan.mywish.io) to NeoRPC.cs file as PrivateNet.

I have added the following lines, but it does not work. 

Could you help me about how to add MyWish as RemoteRPCNode?

Thank you.

```
public static NeoRPC ForPrivateNet()
        {
            return new RemoteRPCNode(20332, "http://neo.mywish.io", NEONodesKind.MYWISH);
        }
```

Also, I have added this code structure to NeoRPC.cs file.

```
 case NEONodesKind.MYWISH:
                    {
                        nodes = new string[4];
                        for (int i = 0; i < nodes.Length; i++)
                        {
                            nodes[i] = $"http://neo.mywish.io:{port}";
                            port = port + 1;
                        }
                        break;
                    }
```

**Comment by uvmetal** [comment]
Did you add `MYWISH` to the `NEONodesKind` structure shown below?

https://github.com/CityOfZion/neo-lux/blob/8f06ea73779c89b3fd3dafd9fa810f17c1fc581c/Neo.Lux/Core/NeoRPC.cs#L347

**Comment by alibugra** [comment]
> Did you add `MYWISH` to the `NEONodesKind` structure shown below?
> 
> https://github.com/CityOfZion/neo-lux/blob/8f06ea73779c89b3fd3dafd9fa810f17c1fc581c/Neo.Lux/Core/NeoRPC.cs#L347

Of course, I have added it.

**Comment by alibugra** [comment]
OK, I have solved by changing port to 30332.
